#!/usr/bin/env python3
"""Single source-of-truth translator: robot.yaml -> compose env-file + bridge.conf.

robot.yaml is the ONLY authored config for a robot host. This script compiles it
into the derived artifacts the stack actually consumes:
  * a generated env-file    -> docker compose --env-file (variable interpolation)
  * docker/mosquitto/bridge.conf (rendered from bridge.conf.template)

Both deploy.sh and (later) the webapp's Apply flow call this, so the CLI and the
web UI can never drift. Keep ALL yaml->env derivation logic here and nowhere else.

Usage:
  render_config.py --config robot.yaml --emit-env .compose.env --render-bridge
  render_config.py --config robot.yaml --set identity.robot=cmexamini \
                   --set images.robot_version=jazzy-1.2.3 --write   # persist edits
  render_config.py --config robot.yaml --print ROBOT ROBOT_INSTANCE  # read values
  render_config.py --migrate-env .env --config robot.yaml           # .env -> yaml
"""
import argparse
import os
import sys

try:
    import yaml
except ImportError:
    sys.exit("render_config: PyYAML is required "
             "(apt install python3-yaml, or pip install pyyaml)")

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BRIDGE_TEMPLATE = os.path.join(REPO_ROOT, "docker/mosquitto/bridge.conf.template")
BRIDGE_OUT = os.path.join(REPO_ROOT, "docker/mosquitto/bridge.conf")

# Defaults preserve the production mecanum robot when a field is absent.
DEFAULTS = {
    "robot": "cmexaiii",
    "domain_id": 12,
    "robot_env": "house",
}


def load(path):
    if not path or not os.path.exists(path):
        return {}
    with open(path) as f:
        data = yaml.safe_load(f) or {}
    if not isinstance(data, dict):
        raise SystemExit(f"render_config: {path} is not a mapping")
    return data


def _set_dotted(cfg, dotted, value):
    """cfg['a']['b'] = value for dotted='a.b'."""
    keys = dotted.split(".")
    node = cfg
    for k in keys[:-1]:
        node = node.setdefault(k, {})
        if not isinstance(node, dict):
            raise SystemExit(f"render_config: cannot set '{dotted}' (not a mapping at '{k}')")
    node[keys[-1]] = value


def _coerce(value):
    """Turn a CLI string into int/bool/str for yaml storage."""
    if value.lower() in ("true", "false"):
        return value.lower() == "true"
    try:
        return int(value)
    except ValueError:
        return value


def resolve(cfg):
    """Compute the derived env vars the compose stack consumes.

    Mirrors (and is the single home of) the identity resolution rules that used
    to live inline in deploy.sh.
    """
    ident = cfg.get("identity", {}) or {}
    ros = cfg.get("ros", {}) or {}
    images = cfg.get("images", {}) or {}
    host = cfg.get("host", {}) or {}

    robot = ident.get("robot") or DEFAULTS["robot"]
    instance = ident.get("instance") or f"{robot}-001"
    domain = ros.get("domain_id", DEFAULTS["domain_id"])
    robot_env = ros.get("robot_env") or DEFAULTS["robot_env"]

    # nav launch: use the authored value only if it belongs to this robot,
    # else fall back to the robot's mapping launch (auto-corrects a stale
    # cross-robot value, matching the old deploy.sh behaviour).
    nav_launch = ros.get("nav_launch") or ""
    if not nav_launch or not nav_launch.startswith(f"{robot}_"):
        nav_launch = f"{robot}_nav_mapping.launch.py"

    hardware_launch = f"{robot}_hardware.launch.py"

    robot_version = images.get("robot_version") or ""
    webapp_version = images.get("webapp_version") or ""
    if not webapp_version or webapp_version == "latest":
        webapp_version = robot_version

    return {
        "ROBOT": robot,
        "ROBOT_INSTANCE": instance,
        "ROS_DOMAIN_ID": str(domain),
        "ROBOT_ENV": robot_env,
        "LAUNCH_FILE": nav_launch,
        "HARDWARE_LAUNCH_FILE": hardware_launch,
        "ROBOT_VERSION": robot_version,
        "WEBAPP_VERSION": webapp_version,
        "INPUT_GID": str(host.get("input_gid", "")),
    }


def emit_env(env, path):
    lines = ["# GENERATED by render_config.py from robot.yaml — do not edit.\n"]
    for k, v in env.items():
        lines.append(f"{k}={v}\n")
    with open(path, "w") as f:
        f.writelines(lines)


def render_bridge(robot, instance):
    if not os.path.exists(BRIDGE_TEMPLATE):
        return
    with open(BRIDGE_TEMPLATE) as f:
        text = f.read()
    text = text.replace("__ROBOT_INSTANCE__", instance).replace("__ROBOT__", robot)
    with open(BRIDGE_OUT, "w") as f:
        f.write(text)


# Map flat .env keys -> dotted robot.yaml paths (for one-shot migration).
ENV_TO_YAML = {
    "ROBOT": "identity.robot",
    "ROBOT_INSTANCE": "identity.instance",
    "ROS_DOMAIN_ID": "ros.domain_id",
    "LAUNCH_FILE": "ros.nav_launch",
    "ROBOT_ENV": "ros.robot_env",
    "ROBOT_VERSION": "images.robot_version",
    "WEBAPP_VERSION": "images.webapp_version",
    "INPUT_GID": "host.input_gid",
}


def migrate_env(env_path, cfg):
    """Fold legacy .env values into cfg (only keys not already set)."""
    if not os.path.exists(env_path):
        return cfg
    for line in open(env_path):
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, val = line.partition("=")
        key, val = key.strip(), val.strip()
        dotted = ENV_TO_YAML.get(key)
        if dotted and val:
            _set_dotted(cfg, dotted, _coerce(val))
    return cfg


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--config", required=True, help="path to robot.yaml")
    ap.add_argument("--set", action="append", default=[], metavar="dotted.key=value",
                    help="override a value (repeatable); persisted with --write")
    ap.add_argument("--migrate-env", metavar="ENV", help="fold a legacy .env into the config")
    ap.add_argument("--write", action="store_true", help="persist the config back to --config")
    ap.add_argument("--emit-env", metavar="PATH", help="write the generated compose env-file")
    ap.add_argument("--render-bridge", action="store_true", help="render docker/mosquitto/bridge.conf")
    ap.add_argument("--print", nargs="*", metavar="VAR", default=None,
                    help="print resolved VAR(s) as KEY=VALUE (all if none given)")
    args = ap.parse_args()

    cfg = load(args.config)

    if args.migrate_env:
        cfg = migrate_env(args.migrate_env, cfg)

    for pair in args.set:
        if "=" not in pair:
            raise SystemExit(f"render_config: --set expects dotted.key=value, got '{pair}'")
        key, _, val = pair.partition("=")
        _set_dotted(cfg, key.strip(), _coerce(val.strip()))

    if args.write:
        with open(args.config, "w") as f:
            yaml.safe_dump(cfg, f, sort_keys=False, default_flow_style=False)

    env = resolve(cfg)

    if args.emit_env:
        emit_env(env, args.emit_env)

    if args.render_bridge:
        render_bridge(env["ROBOT"], env["ROBOT_INSTANCE"])

    if args.print is not None:
        keys = args.print or list(env.keys())
        for k in keys:
            print(f"{k}={env.get(k, '')}")


if __name__ == "__main__":
    main()
